[package]
name = "baryon"
version = "0.2.0"
edition = "2018"
resolver = "2"
license = "MIT"
description = "Fast prototyping 3D engine"
repository = "https://github.com/kvark/baryon"

[workspace]
members = ["baryon-core"]

[features]

[dependencies.baryon-core]
path = "baryon-core"
#version = "0.1"

[dependencies]
log = "0.4"
mint = "0.5"
raw-window-handle = "0.3"
wgpu = "0.10"
winit = "0.25"

[dev-dependencies]
pollster = "0.2"
